### PR TITLE
Python3 compat

### PR DESCRIPTION
**Pull request by kozo2**
I applied 2to3 and disabled SOAPpy.
It seems that SOAPpy does not work with Python3, and the KEGG and PubChem SOAP services are deprecated now.

### CODE REVIEW

**Comment by hredestig** [comment]
Hey thanks for this! With the renewed interest I would just first like to write some tests for this package first... Easter is here so will find some time to do that.

**Comment by kozo2** [comment]
OK.
I may be able to send some pull requests for testing.
In that case, I think I will use pytest for it.

**Comment by hredestig** [comment]
Let me have a go at it to start, then you can make pull requests against that, won't take long. Will definitely use pytest.

**Comment by kozo2** [comment]
Thanks, then I will wait for a while.

**Comment by hredestig** [comment]
Alright, the tests I added are obviously very low coverage but it's a start. I'm sure many things are broken but I more feel like an extensive overhaul (rewrite) of the package than trying to sort out all the details incrementally... Lots of things to consider, particularly switching to neo4j as backend and using their OGM to avoid the whole `mask` class.

**Comment by hredestig** [comment]
Anyway, cheers for the PR, are you working with @afukushima now?

**Comment by kozo2** [comment]
Thanks. I checked your pytest tests.
From now on I will check (and add) the tests on Windows.
I sent you a pull request for Windows CI #3 
I understand your plan to move to neo4j.
Yes. @afukushima and I do not belong to the same lab (and center), but I work with him.

**Pull request merged**
